In [99]:
import os
import pandas as pd
base_dir = './kdef/KDEF/'
path = []
emotion = []
angles = []
index = []

for i, j, k in os.walk(base_dir):
#     print(k)
    for img in k:
        name = img.split('.')[0]
        No = name[:4]
        expression = name[4:6]
        angle = name[6:]
        swtich_expression = {
            "AF": 0,
            "AN": 1,
            "DI": 2,
            "HA": 3,
            "NE": 4,
            "SA": 5,
            "SU": 6
        }
        switch_angle = {
            "FL": 0,
            "FR": 1,
            "HL": 2,
            "HR": 3,
            "S" : 4
        }
        
        path.append('kdef/KDEF/'+No + '/' + img) 
        index.append(No)
        emotion.append(swtich_expression[expression])
        angles.append(switch_angle[angle])
       
        
dict = {
        "index" : index,
        "path" : path,
        "angle" : angles,
        "emotion" : emotion,
        
    }
data = pd.DataFrame(dict)
print(data)

     index                         path  angle  emotion
0     BF07   kdef/KDEF/BF07/BF07SAS.JPG      4        5
1     BF07  kdef/KDEF/BF07/BF07SAFL.JPG      0        5
2     BF07  kdef/KDEF/BF07/BF07NEHR.JPG      3        4
3     BF07  kdef/KDEF/BF07/BF07SAHL.JPG      2        5
4     BF07  kdef/KDEF/BF07/BF07DIHR.JPG      3        2
...    ...                          ...    ...      ...
4893  AM10  kdef/KDEF/AM10/AM10HAHR.JPG      3        3
4894  AM10  kdef/KDEF/AM10/AM10SAHR.JPG      3        5
4895  AM10  kdef/KDEF/AM10/AM10SAFL.JPG      0        5
4896  AM10  kdef/KDEF/AM10/AM10NEFR.JPG      1        4
4897  AM10   kdef/KDEF/AM10/AM10HAS.JPG      4        3

[4898 rows x 4 columns]


In [100]:
import dlib
import cv2
import numpy as np
from skimage import io

predictor_path = "shape_predictor_68_face_landmarks.dat"

detector = dlib.get_frontal_face_detector()
predictor = dlib.shape_predictor(predictor_path)

neutral = data[(data['emotion'] == 4) &  (data['angle'] == 4)]

others = data[(data['emotion'] != 4) &  (data['angle'] == 4)]

print(others)

print(neutral.iloc[1,1])
dict ={}
dict2 ={}
for i in range(68):
    dict['F'+str(i)]=[]
    dict2['F'+str(i)]=[]
    
    
dict['index']=[]
for i,row in neutral.iterrows():
    img = cv2.imread(row['path'])

    dets = detector(img)
    dict['index'].append(row['index'])
    if len(dets):
         shape = predictor(img, dets[0])
         
         for b in range(68):
            x = shape.part(b).x
            y = shape.part(b).y
            # print(shape.part(b))
            dict['F'+str(b)].append(np.array([x,y]))
                
                # cv2.circle(img=img, center=(x, y), radius=3, color=(0, 255, 0), thickness=-1)

            # cv2.imshow(winname="Face", mat=img)
            # cv2.waitKey(1000)
            # # To close the window after the required kill value was provided
            # cv2.destroyAllWindows()


dict2['index']=[]
for i,row in others.iterrows():
    print(i)
    img = cv2.imread(row['path'])

    dets = detector(img)
    dict2['index'].append(row['index'])
    if len(dets):
         shape = predictor(img, dets[0])
        #  for j in range(68):
        #     others.iloc[i]['F'+str(j)]=[]
         t1=[]
         for b in range(68):
            x = shape.part(b).x
            y = shape.part(b).y
            dict2['F'+str(b)].append(np.array([x,y]))






            

   

     index                        path  angle  emotion
0     BF07  kdef/KDEF/BF07/BF07SAS.JPG      4        5
13    BF07  kdef/KDEF/BF07/BF07AFS.JPG      4        0
17    BF07  kdef/KDEF/BF07/BF07SUS.JPG      4        6
19    BF07  kdef/KDEF/BF07/BF07ANS.JPG      4        1
30    BF07  kdef/KDEF/BF07/BF07DIS.JPG      4        2
...    ...                         ...    ...      ...
4882  AM10  kdef/KDEF/AM10/AM10DIS.JPG      4        2
4886  AM10  kdef/KDEF/AM10/AM10AFS.JPG      4        0
4887  AM10  kdef/KDEF/AM10/AM10SAS.JPG      4        5
4888  AM10  kdef/KDEF/AM10/AM10SUS.JPG      4        6
4897  AM10  kdef/KDEF/AM10/AM10HAS.JPG      4        3

[840 rows x 4 columns]
kdef/KDEF/BM11/BM11NES.JPG
0
13
17
19
30
32
36
39
44
55
57
62
81
89
95
97
103
104
111
114
116
119
124
132
142
156
162
170
172
173
175
177
181
192
203
206
218
230
235
237
239
241
261
262
270
272
276
277
286
287
304
307
308
312
319
324
327
328
340
347
354
357
368
375
378
382
396
400
404
405
409
410
421
426
436
437
45

In [105]:
odf = pd.DataFrame(dict2)
print(dict2)
new = pd.merge(others,odf, how='inner')
new1 = new.drop_duplicates(subset="path")
print(new1)
new1.to_csv("new.csv")

2]), array([254, 546]), array([259, 527]), array([259, 549]), array([258, 546]), array([267, 550]), array([265, 533]), array([264, 521]), array([265, 553]), array([266, 567]), array([258, 533]), array([260, 552]), array([264, 542]), array([268, 548]), array([264, 570]), array([261, 582]), array([268, 540]), array([259, 548]), array([272, 535]), array([267, 543]), array([272, 532]), array([274, 553]), array([272, 541]), array([269, 531]), array([266, 565]), array([261, 543]), array([278, 545]), array([273, 544]), array([266, 570]), array([269, 538]), array([260, 547]), array([265, 569]), array([264, 562]), array([269, 547]), array([267, 546]), array([261, 546]), array([258, 548]), array([260, 539]), array([263, 546]), array([264, 552]), array([265, 548]), array([264, 562]), array([260, 561]), array([252, 544]), array([261, 533]), array([264, 537]), array([263, 557]), array([258, 557]), array([265, 554]), array([270, 606]), array([257, 564]), array([265, 549]), array([255, 551]), array([

In [102]:
# neutral.join(dict)
import pandas as pd

ndf = pd.DataFrame(dict)
out = pd.merge(neutral,ndf, how='inner')
out1 = out.drop_duplicates(subset='index')
print(out1)
out1.to_csv("out.csv")

    index                        path  angle  emotion          F0          F1  \
0    BF07  kdef/KDEF/BF07/BF07NES.JPG      4        4  [143, 387]  [142, 424]   
1    BM11  kdef/KDEF/BM11/BM11NES.JPG      4        4  [127, 414]  [133, 453]   
2    BM27  kdef/KDEF/BM27/BM27NES.JPG      4        4  [123, 386]  [125, 428]   
3    BF29  kdef/KDEF/BF29/BF29NES.JPG      4        4  [107, 390]  [110, 433]   
4    BM33  kdef/KDEF/BM33/BM33NES.JPG      4        4  [122, 407]  [126, 448]   
..    ...                         ...    ...      ...         ...         ...   
135  BF26  kdef/KDEF/BF26/BF26NES.JPG      4        4  [122, 386]  [124, 428]   
136  BM04  kdef/KDEF/BM04/BM04NES.JPG      4        4  [127, 391]  [130, 433]   
137  AF23  kdef/KDEF/AF23/AF23NES.JPG      4        4  [115, 390]  [120, 432]   
138  BF10  kdef/KDEF/BF10/BF10NES.JPG      4        4  [113, 402]  [118, 444]   
139  AM10  kdef/KDEF/AM10/AM10NES.JPG      4        4  [128, 380]  [132, 422]   

             F2          F3

In [1]:
import pandas as pd
import numpy as np
df_n = pd.read_csv("out.csv")
df_o = pd.read_csv("new.csv")
dict = {1:[55,49],
        2:[41,39],
        3:[48,44],
        4:[43,25],
        5:[58,52],
        6:[40,37],
        7:[46,43],
        8:[40,20],
        9:[23,22]
}
dataset = df_o.iloc[:,1:4]
emotion = df_o.iloc[:,4]
dataset['id'] = range(len(dataset))
print(dataset)

def distance(a,b):
    
    a = a[1:-1]
    b = b[1:-1]
    
    a = a.split(' ')
    b = b.split(' ')
    print(a)
    p1 = np.array([int(a[0]),int(a[1])])
    p2 = np.array([int(b[0]),int(b[1])])
    return np.linalg.norm(p1-p2)

def dist(a,b):
    
    a = a.to_numpy()[0]
    b = b.to_numpy()[0]
 
    a = a[1:-1]
    b = b[1:-1]
    a = a.split(' ')
    b = b.split(' ')
    p1 = np.array([int(a[0]),int(a[1])])
    p2 = np.array([int(b[0]),int(b[1])])
    return np.linalg.norm(p1-p2)
    
# print(df_o)
temp = []
for i,row in df_o.iterrows():
    #  print(i,row['index'])
    #  print(row[dict[j+1][0]-4],row[dict[j+1][1]-4])
     t=[]
     for j in range(9):
         print((row[dict[j+1][0]-4],row[dict[j+1][1]-4]))
         print(df_n[df_n['index']==row['index']].iloc[:,dict[j+1][0]-4],df_n[df_n['index']==row['index']].iloc[:,dict[j+1][1]-4])
         dis_o = distance(row[dict[j+1][0]-4],row[dict[j+1][1]-4])
         dis_n = dist(df_n[df_n['index']==row['index']].iloc[:,dict[j+1][0]-4],df_n[df_n['index']==row['index']].iloc[:,dict[j+1][1]-4])
         
         t.append( dis_o - dis_n )
     temp.append(t)
tt = pd.DataFrame(temp)
print(tt)





e: F49, dtype: object 137    [341 374]
Name: F43, dtype: object
['250', '546']
('[249 503]', '[278 422]')
137    [253 497]
Name: F31, dtype: object 137    [280 416]
Name: F28, dtype: object
['249', '503']
('[196 379]', '[298 508]')
137    [195 379]
Name: F37, dtype: object 137    [298 501]
Name: F34, dtype: object
['196', '379']
('[249 503]', '[381 575]')
137    [253 497]
Name: F31, dtype: object 137    [385 576]
Name: F11, dtype: object
['249', '503']
('[432 459]', '[421 500]')
137    [427 463]
Name: F14, dtype: object 137    [419 503]
Name: F13, dtype: object
['432', '459']
('[369 391]', '[217 398]')
137    [369 396]
Name: F46, dtype: object 137    [217 404]
Name: F40, dtype: object
['369', '391']
('[264 509]', '[278 490]')
137    [267 502]
Name: F32, dtype: object 137    [281 476]
Name: F30, dtype: object
['264', '509']
('[239 394]', '[314 501]')
137    [239 398]
Name: F39, dtype: object 137    [312 494]
Name: F35, dtype: object
['239', '394']
('[298 508]', '[444 373]')
137    [298 

In [12]:
data = pd.DataFrame(tt)
# emotion = emotion.to_numpy()


from keras.regularizers import l2
from keras.models import Sequential
from keras.layers import Dense
from sklearn.model_selection import train_test_split
from sklearn import svm
from sklearn import metrics
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import KFold
from sklearn.preprocessing import LabelEncoder
from keras.wrappers.scikit_learn import KerasClassifier
from sklearn.pipeline import Pipeline
from keras.utils import np_utils
from sklearn.model_selection import cross_val_score

scalar = StandardScaler()

X = scalar.fit_transform(data)
print(X)

encoder = LabelEncoder()
encoder.fit(emotion)
y = encoder.transform(emotion)
# convert integers to dummy variables (i.e. one hot encoded)
dummy_y = np_utils.to_categorical(y)

print(dummy_y)


# X_train, X_test, y_train, y_test = train_test_split(data, dummy_y, test_size=0.33, random_state=42)   

def baseline_model():
	# create model
	model = Sequential()
	model.add(Dense(64, activation='relu'))
	model.add(Dense(128, activation='relu'))
	model.add(Dense(6, activation='softmax'))
	# Compile model
	model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
	return model

estimator = KerasClassifier(build_fn=baseline_model, epochs=10, batch_size=5, verbose=1)
print(estimator)
kfold = KFold(n_splits=5, shuffle=True)
print(kfold)
results = cross_val_score(estimator, X, dummy_y, cv=kfold)
print(results)
print("Baseline: %.2f%% (%.2f%%)" % (results.mean()*100, results.std()*100))

# # model = Sequential()
# # model.add(Dense(64, activation='relu'))
# # model.add(Dense(1, activation='softmax'))

# # model.compile(loss='hinge',
# #               optimizer='adam',
# #               metrics=['accuracy'])
# # model.fit(X_train, y_train)

# # y_pred = model.predict(X_test)

# # print(y_pred)

# # print(metrics.accuracy_score(y_test,y_pred))

# model = KNeighborsClassifier(n_neighbors=6)

# model.fit(X_train,y_train)

# y_pred = model.predict(X_train)

# print(y_pred)

# print(metrics.accuracy_score(y_train,y_pred))

# con = confusion_matrix(y_train,y_pred,[0,1,2,3,5,6])

# print(con)

# model = baseline_model()

# model.fit(X,dummy_y)

# print(model.predict(X))




[[-0.30394847 -0.8545616   0.42325828 ...  0.19208819 -0.7272872
  -0.15296894]
 [-0.30394847 -0.8545616   0.42325828 ...  0.19208819 -0.7272872
  -0.15296894]
 [-0.30394847 -0.8545616   0.42325828 ...  0.19208819 -0.7272872
  -0.15296894]
 ...
 [ 1.18434123 -0.86289761  1.18174177 ...  1.16543351  0.67993817
   1.39108927]
 [ 1.18434123 -0.86289761  1.18174177 ...  1.16543351  0.67993817
   1.39108927]
 [ 1.18434123 -0.86289761  1.18174177 ...  1.16543351  0.67993817
   1.39108927]]
[[0. 0. 0. 0. 1. 0.]
 [1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1.]
 ...
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0.]]
KFold(n_splits=5, random_state=None, shuffle=True)
Epoch 1/10
135/135 [==============================] - 0s 2ms/step - loss: 1.8470 - accuracy: 0.1235
Epoch 2/10
135/135 [==============================] - 0s 3ms/step - loss: 1.8203 - accuracy: 0.1443
Epoch 3/10
135/135 [==============================] - 0s 3ms/step - loss: 1.8132 - accuracy: 0.1488
Epoch 4/10
135/135 [========